<?php
	/**
	 * @var Suivi $uneSuivi
	 * @var Projet $unProjet
	 * @var Apprenant $unApprenant
	 *
	 */
?>
<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require "includes/core/views/partials/page_head.phtml"; ?>
</head>
<body>
	<main>
		<header>
			<?php require "includes/core/views/partials/page_header.phtml"; ?>
		</header>
		<nav>
			<?php require_once "includes/core/views/partials/navbar.phtml"; ?>
		</nav>
		<section id="content">
			<?= $message ?? '' ?>
			<form action="" method="post">
				<header>
					<h3>Projet : <a title="Voir le projet" href="index.php?page=projet&action=view&id=<?= $unProjet->getId() ?>"><?= $unProjet->getNom() ?></a></h3>
					<h3>Auteur : <a title="Voir les projets de l'apprenant" href="index.php?page=projet&action=list&idapprenant=<?= $unApprenant->getId() ?>"><?= $unApprenant->getFullName() ?></a></h3>
				</header>
				<div class="field">
					<label for="champDateSuivi">Date de suivi : </label>
					<div>
						<input type="date" name="chDateSuivi" id="champDateSuivi" value="<?= $unSuivi->getDateSuivi()->format('Y-m-d') ?>" placeholder="Saisir la date de suivi" required/>
						<span></span>
					</div>
				</div>
				<div class="field">
					<label for="champCommentaires">Commentaires: </label>
					<div>
						<textarea name="chCommentaires" id="champCommentaires" placeholder="Saisir les commentaire" required><?= $unSuivi->getCommentaire() ?></textarea>
						<span></span>
					</div>
				</div>
				<div class="field">
					<label for="champCbIntervenant">Intervenant : </label>
					<div>
						<select name="chCbIntervenant" id="champCbIntervenant" required>
							<option value="0"> -- Sélectionner -- </option>
							<?php
								$script = '';
								foreach ($lesIntervenants as $unIntervenant){
									if ($unIntervenant->getId() == $unSuivi->getIntervenant()->getId()){
										$script .= '<option value="'.$unIntervenant->getId().'" selected>'.$unIntervenant->getFullName().'</option>';
									}else{
										$script .= '<option value="'.$unIntervenant->getId().'">'.$unIntervenant->getFullName().'</option>';
									}
								}
								print($script);
							?>
						</select>
						<span></span>
					</div>
				</div>
				<div class="actions">
					<button class="btn btn-submit" type="submit">Valider</button>
					<button class="btn btn-cancel" type="reset">Réinitialiser</button>
				</div>
			</form>
		</section>
		<footer>
			<?php require_once "includes/core/views/partials/footer.phtml"; ?>
		</footer>
	</main>
	<script src="public/scripts/common_functions.js"></script>
</body>
</html>
