<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require "includes/core/views/partials/page_head.phtml"; ?>
</head>
<body>
	<main>
		<header>
			<?php require "includes/core/views/partials/page_header.phtml"; ?>
		</header>
		<nav>
			<?php require_once "includes/core/views/partials/navbar.phtml"; ?>
		</nav>
		<section id="content">
			<form action="" method="post">
				<div>
					<label for="chCbCivilite">Civilite</label>
					<select name="cbCivilite" id="chCbCivilite">
						<option value="0">-- Sélectionner --</option>
						<?php
							foreach ($lesCivilites as $civilite){
								if ($civilite->getId() == $unePersonne->getCivilite()->getId()){
									print('<option value="'.$civilite->getId().'" selected>'.$civilite->getLibelleLong().'</option>');
								}else{
									print('<option value="'.$civilite->getId().'">'.$civilite->getLibelleLong().'</option>');
								}
							}
						?>
					</select>
				</div>
				<div>
					<label for="champNom">Nom : </label><input type="text" name="chNom" id="champNom" value="<?= $unePersonne->getNom() ?>">
				</div>
				<div>
					<label for="champPrenom">Prénom : </label><input type="text" name="chPrenom" id="champPrenom" value="<?= $unePersonne->getPrenom() ?>">
				</div>
				<div>
					<label for="champDateNaissance">Date de naissance : </label><input type="date" name="chDateNaissance" id="champDateNaissance" value="<?= $unePersonne->getDateNaissance()->format('Y-m-d') ?>">
				</div>
				<div>
					<div>
						<label for="champNumRue">Numéro : </label><input type="text" name="chNumRue" id="champNumRue" value="<?= $unePersonne->getNumRue() ?>">
						<label for="champNomRue">Rue : </label><input type="text" name="chNomRue" id="champNomRue" value="<?= $unePersonne->getNomRue() ?>">
					</div>
					<div>
						<label for="champComplementAdresse">Complément : </label><input type="text" name="chComplementAdresse" id="champComplementAdresse" value="<?= $unePersonne->getComplementRue() ?>">
					</div>
				</div>
				<div>
					<label for="champCpVille">Code postal / Ville : </label>
					<select id="champCpVille" name="chCpVille">
						<option value="0">-- Sélectionner --</option>
						<?php
							foreach ($lesCpVilles as $CpVille){
								if ($CpVille->getId() == $unePersonne->getCpVille()->getId()){
									print('<option value="'.$CpVille->getId().'" selected>'.$CpVille->getCodePostal().' '.$CpVille->getVille().'</option>');
								}else{
									print('<option value="'.$CpVille->getId().'">'.$CpVille->getCodePostal().' '.$CpVille->getVille().'</option>');
								}

							}
						?>
					</select>
				</div>
				<div>
					<label for="champTaille">Taille : </label>
					<input type="number" name="chTaille" id="champTaille" value="<?= $unePersonne->getTaille() ?>">
				</div>
				<div>
					<label for="champPoids">Poids : </label>
					<input type="number" name="chPoids" id="champPoids" value="<?= $unePersonne->getPoids() ?>">
				</div>
				<div class="actions">
					<button class="btn btn-submit" type="submit" name="btSubmit">Valider</button>
					<button class="btn btn-cancel" type="reset">Réinitialiser</button>
				</div>
			</form>
		</section>
		<?= $message ?? '' ?> 
		<footer>
			<?php require_once "includes/core/views/partials/footer.phtml"; ?>
		</footer>
	</main>
	<script src="public/scripts/common_functions.js"></script>
</body>
</html>
