<?php
/**
 * @var Projet $unProjet
 * @var Fonctionnalite $uneFonctionnalite
 * @var Technologie $uneTechnologie
 * @var Suivi $unSuivi
 * @var Apprenant $unApprenant
 * @var bool $enableActions
 */
?>
<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require "includes/core/views/partials/page_head.phtml"; ?>
</head>
<body>
	<main>
		<header>
			<?php require "includes/core/views/partials/page_header.phtml"; ?>
		</header>
		<nav>
			<?php require_once "includes/core/views/partials/navbar.phtml"; ?>
		</nav>
		<section id="content" class="projet">
			<article>
				<header>
					<h1><?= $unProjet->getNom() ?></h1>
				</header>
				<div>
					<h3>Auteur : <a title="Voir les projets de l'apprenant" href="index.php?page=projet&action=list&idapprenant=<?= $unApprenant->getId() ?>"><?= $unApprenant->getFullName() ?></a></h3>
					<h3>Promotion : <a title="Voir la liste des apprenants de la promotion" href="index.php?page=apprenant&action=list&idpromo=<?= $unApprenant->getPromotion()->getId() ?>"><?= $unApprenant->getPromotion()->getNom() ?></a></h3>
					<h3>Début : <?= $unProjet->getDateDebut()->format('d/m/Y') ?></h3>
				</div>
				<section>
					<h3>Présentation : </h3>
					<p>
						<?= nl2br($unProjet->getPresentation()) ?>
					</p>
					<h3>Spécificités :</h3>
					<p>
						<?= nl2br($unProjet->getSpecificites()) ?>
					</p>
					<h3>Evolutions :</h3>
					<p>
						<?= nl2br($unProjet->getEvolutions()) ?>
					</p>
				</section>
				<section class="fonctionnalites">
					<a id="fonctionnalites"></a>
					<h3>Fonctionnalités : <?= ($enableActions ? '<a title="Nouvelle fonctionnalité" href="index.php?page=fonctionnalite&action=add&idprojet='.$unProjet->getId().'"><img class="mini w-12 h-12" src="./public/medias/plus_blue.png"/></a>' : '') ?></h3>
					<?php
						if ($unProjet->getNbFonctionnalites() == 0){
							$script = "<p>Aucune fonctionnalité n'est actuellement associée à ce projet !</p>";
						}else{
							$script = '<ul>';
							foreach ($unProjet->getFonctionnalites() as $uneFonctionnalite){
								$script .= '<li>';
								$script .= $uneFonctionnalite->getLibelle();
								if ($enableActions){
									$script .= '<a href="index.php?page=fonctionnalite&action=edit&id='.$uneFonctionnalite->getId().'" title="Modifier">';
									$script .= '<img class="mini w-10 h-10" src="./public/medias/stylo_edit.png" alt="Supprimer"/>';
									$script .= '</a>';
									$script .= '<a data-action="deletelink" href="index.php?page=fonctionnalite&action=delete&id='.$uneFonctionnalite->getId().'" title="Supprimer">';
									$script .= '<img class="mini w-10 h-10" src="./public/medias/croix_rouge.png" alt="Supprimer"/>';
									$script .= '</a>';
								}
								$script .= '</li>';
							}
							$script .= '</ul>';
						}
						print($script);
					?>
				</section>
				<section class="technologies">
					<a id="technologies"></a>
					<h3>Technologies : <?= ($enableActions ? '<a title="Nouvelle technologie" href="index.php?page=technologie&action=addtoproject&idprojet='.$unProjet->getId().'"><img class="mini w-12 h-12" src="./public/medias/plus_blue.png"/></a>' : '') ?></h3>
					<?php
						if ($unProjet->getNbTechnologies() == 0){
							$script = "<p>Aucune technologie n'est actuellement associée à ce projet !</p>";
						}else{
							$script = '<ul>';
							foreach ($unProjet->getTechnologies() as $uneTechnologie){
								$script .= '<li>';
								$script .= $uneTechnologie->getLibelle();
								if ($enableActions){
									$script .= '<a data-action="deletelink" href="index.php?page=technologie&action=removefromproject&idprojet=' . $unProjet->getId() . '&idtechnologie=' . $uneTechnologie->getId() . '" title="Supprimer">';
									$script .= '<img class="mini w-10 h-10" src="./public/medias/croix_rouge.png" alt="Supprimer"/>';
									$script .= '</a>';
								}
								$script .= '</li>';
							}
							$script .= '</ul>';
						}
						print($script);
					?>
				</section>
				<section class="suivis">
					<a id="suivis"></a>
					<h3>Suivis : <?= ($enableActions ? '<a title="Nouveau suivi" href="index.php?page=suivi&action=add&idprojet='.$unProjet->getId().'"><img class="mini w-12 h-12" src="./public/medias/plus_blue.png"/></a>' : '') ?></h3>
					<?php
						if ($unProjet->getNbSuivis() == 0){
							$script = "<p>Aucun suivi n'est actuellement associé à ce projet !</p>";
						}else{
							$script = '';
							foreach ($unProjet->getSuivis() as $unSuivi){
								$script .= '<section class="suivi">';
									$script .= '<header>';
										$script .= $unSuivi->getDateSuivi()->format('d/m/Y');
										$script .= ' - par : ';
										$script .= $unSuivi->getIntervenant()->getFullName();
										if ($enableActions){
											$script .= '<a href="index.php?page=suivi&action=edit&id=' . $unSuivi->getId() . '" title="Modifier ce suivi">';
											$script .= '<img class="mini w-16 h-16" src="./public/medias/stylo_edit.png" alt="Supprimer"/>';
											$script .= '</a>';
											$script .= '<a data-action="deletelink" href="index.php?page=suivi&action=delete&id=' . $unSuivi->getId() . '" title="Supprimer ce suivi">';
											$script .= '<img class="mini w-16 h-16" src="./public/medias/croix_rouge.png" alt="Supprimer"/>';
											$script .= '</a>';
										}
									$script .= '</header>';
									$script .= '<p>'.nl2br($unSuivi->getCommentaire()).'</p>';
								$script .= '</section>';
							}
						}
						print($script);
					?>
				</section>
			</article>

		</section>
		<?= $message ?? '' ?> 
		<footer>
			<?php require_once "includes/core/views/partials/footer.phtml"; ?>
		</footer>
	</main>
	<script src="public/scripts/common_functions.js"></script>
</body>
</html>
