<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require "includes/core/views/partials/page_head.phtml"; ?>
</head>
<body>
	<main>
		<header>
			<?php require "includes/core/views/partials/page_header.phtml"; ?>
		</header>
		<nav>
			<?php require_once "includes/core/views/partials/navbar.phtml"; ?>
		</nav>
		<section id="content" class="referentiel">
			<article>
				<header>
					<h1><?= $unReferentiel->getLibelle() ?></h1>
				</header>
				<div>
					<h3>Validité : <?= $unReferentiel->getDateValidite()->format('d/m/Y') ?></h3>
					<h3>RNCP : <?= $unReferentiel->getNumRncp() ?></h3>
				</div>
				<section>
					<h3>Détails : </h3>
					<p>
						<?= $unReferentiel->getDetails() ?>
					</p>
					<h3>Objectifs :</h3>
					<p>
						<?= $unReferentiel->getObjectifs() ?>
					</p>
					<h3>Activites :</h3>
					<p>
						<?= $unReferentiel->getActivites() ?>
					</p>
					<h3>Compétences :</h3>
					<p>
						<?= $unReferentiel->getCompetences() ?>
					</p>
					<h3>Modalités d'évaluation :</h3>
					<p>
						<?= $unReferentiel->getModaliteEvaluation() ?>
					</p>
				</section>
				<section class="bloccompetences">
					<h3>Blocs de compétences : </h3>
					<?php
						$script = '<ul>';
						foreach ($unReferentiel->getBlocscompetences() as $blocscompetence){
							$script .= '<li>'.$blocscompetence->getLibelle();

							if (count($blocscompetence->getCompetences()) > 0){
								$script .= '<ul>';
								foreach ($blocscompetence->getCompetences() as $competence){
									$script .= '<li>'.$competence->getLibelle().'</li>';
								}
								$script .= '</ul>';
							}

							$script .= '</li>';
						}
						$script .= '</ul>';
						print($script);
					?>
				</section>
			</article>

		</section>
		<?= $message ?? '' ?> 
		<footer>
			<?php require_once "includes/core/views/partials/footer.phtml"; ?>
		</footer>
	</main>
	<script src="public/scripts/common_functions.js"></script>
</body>
</html>
