<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="fr">
	<head>
		<?php require "includes/core/views/partials/page_head.phtml"; ?>
	</head>
	<body>
		<main>
			<header>
				<?php require "includes/core/views/partials/page_header.phtml"; ?>
			</header>
			<nav>
				<?php require_once "includes/core/views/partials/navbar.phtml"; ?>
			</nav>
			<section id="content" class="vertical-center">
				Application minimaliste de suivi des projets
			</section>
			<footer>
				<?php require_once "includes/core/views/partials/footer.phtml"; ?>
			</footer>
		</main>
		<script src="./public/scripts/common_functions.js"></script>
	</body>
</html>
