<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
	<main>
		<header>
				<?php require "includes/partials/page_header.phtml"; ?>
			</header>
			<nav>
				<?php require_once "includes/partials/navbar.phtml"; ?>
			</nav>
			<section id="content">
			<a href="index.php?page=contact&action=add">Ajouter un contact</a>
			<table>
				<thead>
					<th>Nom</th>
					<th>Prenom</th>
					<th>Date Naissance</th>
					<th colspan="2">Actions</th>
				</thead>
				<tbody>
					<?php
					foreach ($lesContacts as $unContact){
						print('<tr>');
						print('<td>'.$unContact->getNom().'</td>');
						print('<td>'.$unContact->getPrenom().'</td>');
						print('<td>'.$unContact->getDateNaissance()->format('d/m/Y').'</td>');
						print("<td><a href=\"index.php?page=contact&action=edit&id={$unContact->getId()}\">Modifier</a></td>");
						print('<td><a href="index.php?page=contact&action=delete&id='.$unContact->getId().'">Supprimer</a></td>');
						print('</tr>');
					}
					?>
				</tbody>

			</table>
			<pre>
				<?php 
					//print_r($lesContacts);
				?>
			</pre>
		</section>
		<footer>
			<?php require_once "includes/partials/footer.phtml"; ?>
		</footer>
		<script src="public/scripts/common_functions.js"></script>
	</main>
</body>
</html>
