<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require "includes/core/views/partials/page_head.phtml"; ?>
</head>
<body>
	<main>
		<header>
			<?php require "includes/core/views/partials/page_header.phtml"; ?>
		</header>
		<nav>
			<?php require_once "includes/core/views/partials/navbar.phtml"; ?>
		</nav>
		<section id="content" class="flexcol">
			<h2>
				Apprenants de la promo <?= $unePromo->getNom(); ?>
			</h2>
			<table class="apprenants">
				<thead>
					<th>Nom</th>
					<th>Prenom</th>
					<th>Email</th>
					<th colspan="2">Actions</th>
				</thead>
				<caption>
					<a href="index.php?page=apprenant&action=add&idpromo=<?= $idPromo ?>">Ajouter un apprenant</a>
				</caption>
				<tbody>
					<?php
						$script = '';
						foreach ($lesApprenants as $unApprenant){
							$script .= '<tr>';
							$script .= '<td>'.$unApprenant->getNom().'</td>';
							$script .= '<td>'.$unApprenant->getPrenom().'</td>';
							$script .= '<td>'.$unApprenant->getEmail().'</td>';
							$script .= '<td class="actions">';
							$script .= '<a title="Modifier" href="index.php?page=apprenant&action=edit&id='.$unApprenant->getId().'"><img src="./public/medias/edit_blue.png" alt="modifier"></a>';
							$script .= '<a title="Supprimer" data-action="deletelink" href="index.php?page=apprenant&action=delete&id='.$unApprenant->getId().'"><img src="./public/medias/delete_blue.png" alt="modifier"></a>';
							$script .= '<a title="Ses projets" href="index.php?page=projet&action=list&idapprenant='.$unApprenant->getId().'"><img src="./public/medias/projet_blue.png" alt="voir les apprenants"></a>';
							$script .= '</td>';
							$script .= '</tr>';
						}
						print($script);
					?>
				</tbody>

			</table>
		</section>
		<footer>
			<?php require_once "includes/core/views/partials/footer.phtml"; ?>
		</footer>
		<script src="public/scripts/common_functions.js"></script>
	</main>
</body>
</html>
