<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require "includes/core/views/partials/page_head.phtml"; ?>
</head>
<body>
	<main>
		<header>
				<?php require "includes/core/views/partials/page_header.phtml"; ?>
		</header>
		<nav>
			<?php require_once "includes/core/views/partials/navbar.phtml"; ?>
		</nav>
		<section id="content">
			<table class="promotion">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Date Début</th>
						<th>Date Fin</th>
						<th>Nb Apprenants</th>
						<th class="actions" colspan="2">Actions</th>
					</tr>
				</thead>
				<caption>
					<a href="index.php?page=promotion&action=add">Ajouter une promotion</a>
				</caption>
				<tbody>
					<?php
						$script = '';
						foreach ($lesPromotions as $unePromotion){
							$script .= '<tr>';
							$script .= '<td><a title="Voir" href="index.php?page=promotion&action=view&id='.$unePromotion->getId().'">'.$unePromotion->getNom().'</a></td>';
							$script .= '<td>'.$unePromotion->getDateDebut()->format('d/m/Y').'</td>';
							$script .= '<td>'.$unePromotion->getDateFin()->format('d/m/Y').'</td>';
							$script .= '<td>'.$unePromotion->getNbApprenants().'</td>';
							$script .= '<td class="actions">';
							$script .= '<a title="Modifier" href="index.php?page=promotion&action=edit&id='.$unePromotion->getId().'"><img src="./public/medias/edit_blue.png" alt="modifier"></a>';
							$script .= '<a title="Supprimer" data-action="deletelink" href="index.php?page=promotion&action=delete&id='.$unePromotion->getId().'"><img src="./public/medias/delete_blue.png" alt="modifier"></a>';
							$script .= '<a title="Les Apprenants" href="index.php?page=apprenant&action=list&idpromo='.$unePromotion->getId().'"><img src="./public/medias/apprenants_blue.png" alt="voir les apprenants"></a>';
							$script .= '</td>';
							$script .= '</tr>';
						}
						print($script);
					?>
				</tbody>

			</table>
		</section>
		<footer>
			<?php require_once "includes/core/views/partials/footer.phtml"; ?>
		</footer>
	</main>
	<script src="./public/scripts/common_functions.js"></script>
</body>
</html>
